shopifyDomain: 'cherevan.myshopify.com'
shopifyStorefrontToken: '7a50a69f807ec31535e5a23ba3189fee'
GoogleContainerID: 'GTM-TK4NCM7C'
supportedImageThumbnails:
  - jpeg
  - png
  - tiff
  - bmp
  - gif
