[build]
  command = "hugo"
  publish = "public"
  command = "hugo -v --config=./hugo.yaml"

  [build.environment]
    HUGO_VERSION = "0.118.2"
[context.production.environment]
  HUGO_ENV = "production"

