name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        fetch-depth: 1 # Fetches only the latest commit, significantly speeding up checkout
        # lfs: true      # Uncomment if your repository uses Git LFS for large files

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build Tailwind CSS
      run: npm run build

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.118.2'

    - name: Process images
      run: node ./images_process.js

    - name: Build Hugo site
      run: hugo --minify --baseURL="https://www.cherevan.art"

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/769799666531/locations/global/workloadIdentityPools/github-actions-pool'
        service_account: 'github-actions-firebase-deploy@cherevan-art-workspace.iam.gserviceaccount.com'

    - name: Deploy to Firebase Hosting
      uses: firebase-tools/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}' # Optional: Used for GitHub deployment environments
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY_JSON }}' # This will be ignored if google-github-actions/auth is used and successful, but good to have for fallback or other contexts
        channelId: live # Optional: deploy to a specific channel (e.g., live, preview)
        projectId: cherevan-art-workspace
      env:
        FIREBASE_CLI_PREVIEWS: hostingchannels # Optional: if you use hosting channels
