name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        fetch-depth: 1 # Fetches only the latest commit, significantly speeding up checkout
        # lfs: true      # Uncomment if your repository uses Git LFS for large files

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build Tailwind CSS
      run: npm run build

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.118.2'

    - name: Process images
      run: node ./images_process.js

    - name: Build Hugo site
      run: hugo --minify --baseURL="https://www.cherevan.art"

    - name: Authenticate to Google Cloud
      id: auth # Give an id to this step to reference its outputs if needed
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/769799666531/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
        service_account: 'github-actions-firebase-deploy@cherevan-art-workspace.iam.gserviceaccount.com'

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy to Firebase Hosting
      run: firebase deploy --only hosting --project cherevan-art-workspace --non-interactive --debug
      # --non-interactive is good for CI
      # --debug can provide more output if there are issues
      # The project ID is explicitly set for clarity, though it should pick it up from .firebaserc or ADC
