name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        fetch-depth: 1 # Fetches only the latest commit, significantly speeding up checkout
        # lfs: true      # Uncomment if your repository uses Git LFS for large files

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build Tailwind CSS
      run: npm run build

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.118.2'

    - name: Process images
      run: node ./images_process.js

    - name: Build Hugo site
      run: hugo --minify --baseURL="https://www.cherevan.art"

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy to Firebase Hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: firebase deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}"
